import { useEffect, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { useNavigate } from 'react-router-dom';
import { db } from '../../firebase'; import { Button } from '../../components/ui/button'; import { useUser } from '../../contexts/UserContext'; import { useLanguage } from '../../contexts/useTranslation';
import type { UserProfile } from '../../types'; import type { PerformanceProfileSummary } from '../performanceProfile/types'; import { EXERCISE_BY_ID } from '../../data/exercises/library'; import { calendarPlanWeek } from '../planLifecycle';
type Family = 'squat' | 'hinge' | 'push' | 'pull';
const family = (id: string): Family | null => { const p = EXERCISE_BY_ID[id]?.pattern; return p === 'squat' || p === 'lunge' || p === 'knee-extension' ? 'squat' : p === 'hinge' || p === 'hip-extension' || p === 'knee-flexion' ? 'hinge' : p?.includes('press') ? 'push' : p?.includes('pull') ? 'pull' : null; };
export const KaliDashboard = ({ user }: { user: UserProfile }) => { const { updateUserProfile } = useUser(); const { language } = useLanguage(); const navigate = useNavigate(); const pl = language === 'pl';
    const start = user.programProgress?.kali?.startDate ?? user.startDate; const week = Math.min(8, calendarPlanWeek(start, new Date().toISOString())); const [current, setCurrent] = useState<Partial<Record<Family, number>>>({});
    const [bodyweight, setBodyweight] = useState(user.kaliStatus?.bodyweightKg?.toString() ?? ''); const prefs = user.planPreferences?.kali; const [anchor, setAnchor] = useState(prefs?.exerciseSelections?.pullAnchor ?? 'assisted-pull-up'); const [repeat, setRepeat] = useState(prefs?.exerciseSelections?.week8Intensifier ?? '');
    useEffect(() => { void (async () => { const snapshot = await getDocs(collection(db, 'users', user.id, 'performanceProfile')); const latest: Partial<Record<Family, number>> = {};
        snapshot.docs.forEach(doc => { const summary = doc.data() as PerformanceProfileSummary; const f = family(summary.exerciseId); const observation = summary.latestObservation; if (f && observation.estimateConfidence === 'standard' && observation.estimated1RMKg) latest[f] = Math.max(latest[f] ?? 0, observation.estimated1RMKg); }); setCurrent(latest);
        if (!user.kaliStatus?.baseline && Object.keys(latest).length) await updateUserProfile({ kaliStatus: { ...(user.kaliStatus ?? {}), baseline: latest } }); })(); }, [user.id]);
    const save = async () => { const kg = Number(bodyweight.replace(',', '.')); const now = new Date().toISOString(); await updateUserProfile({ kaliStatus: { ...(user.kaliStatus ?? {}), ...(Number.isFinite(kg) && kg > 0 ? { bodyweightKg: kg } : {}) }, planPreferences: { ...(user.planPreferences ?? {}), kali: { scheduleMode: '4day', updatedAt: now, exerciseSelections: { pullAnchor: anchor, ...(repeat ? { week8Intensifier: repeat } : {}) } } } }); };
    return <main className="instrument-page space-y-8"><section className="dashboard-command"><p className="dashboard-command-label">KALI · {pl ? `TYDZIEŃ ${week}` : `WEEK ${week}`}</p><h1>{pl ? 'Zachowaj siłę' : 'Keep the strength'}</h1><p className="text-muted-foreground">{pl ? 'Najpierw redukuj objętość, nie intensywność.' : 'Reduce volume before intensity.'}</p><Button size="lg" className="dashboard-start" onClick={() => navigate(`/app/workout/${week}/1`)}>{pl ? 'Rozpocznij Earth' : 'Start Earth'}</Button></section><section><h2 className="text-2xl font-semibold">{pl ? 'Zachowanie wyników' : 'Performance retained'}</h2><dl className="spec-rows mt-4">{(['squat','hinge','push','pull'] as Family[]).map(f => <div key={f}><dt>{f}</dt><dd>{user.kaliStatus?.baseline?.[f] && current[f] ? `${Math.round(current[f]! / user.kaliStatus.baseline[f]! * 100)}%` : '—'}</dd></div>)}</dl></section>
        <section className="space-y-4"><h2 className="text-xl font-semibold">{pl ? 'Ustawienia biegu' : 'Run settings'}</h2><div className="grid sm:grid-cols-3 gap-4"><label className="text-xs uppercase tracking-widest text-muted-foreground">{pl ? 'Kotwica pull' : 'Pull anchor'}<select value={anchor} onChange={e => setAnchor(e.target.value)} className="block min-h-11 w-full bg-transparent border-b border-input text-base"><option value="weighted-pull-up">Weighted pull-up</option><option value="assisted-pull-up">Assisted pull-up</option><option value="lat-pulldown">Lat pulldown</option></select></label><label className="text-xs uppercase tracking-widest text-muted-foreground">{pl ? 'Masa ciała (opcjonalna)' : 'Bodyweight (optional)'}<input value={bodyweight} onChange={e => setBodyweight(e.target.value)} inputMode="decimal" className="block min-h-11 w-full bg-transparent border-b border-input text-base" /></label><label className="text-xs uppercase tracking-widest text-muted-foreground">{pl ? 'Powtórka tydzień 8' : 'Week 8 repeat'}<select value={repeat} onChange={e => setRepeat(e.target.value)} className="block min-h-11 w-full bg-transparent border-b border-input text-base"><option value="">{pl ? 'Wybierz po tygodniu 7' : 'Choose after week 7'}</option><option value="rest-pause">Rest-pause</option><option value="myo">Myo-reps</option></select></label></div><Button variant="outline" onClick={() => void save()}>{pl ? 'Zapisz' : 'Save'}</Button></section></main>; };
