/**
 * Exercise tips that are not a movement's general coaching cue, keyed by the
 * exact name a plan renders.
 *
 * Prescription-specific ("Conventional Deadlift (ME)", "Paused Bench Press
 * (Light)") and week-scoped special cases. These describe how a set is run on
 * a given day rather than how the movement is performed, so they are
 * intentionally NOT library tips — see library.ts.
 *
 * Generated by scripts/apply-tips.ts from the former WorkoutView tipMap, so
 * library tips + these cover everything that map served.
 */

/** `weeks` restricts a tip to those training weeks; absent means always. */
export type VariantTip = { en: string; pl: string; weeks?: number[] };

export const EXERCISE_VARIANT_TIPS: Record<string, VariantTip[]> = {
    "Conventional Deadlift": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1 (heavy days).', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1 (ciężkie dni).' },
    ],
    "Conventional Deadlift (AMRAP Test)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2. AMRAP test. Perfect form. Determines peaking weights.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2. Test AMRAP. Perfekcyjna forma. Określa ciężary peakingowe.' },
    ],
    "Conventional Deadlift (Ascension Test)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2.  ASCENSION TEST.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2.  TEST ASCENSJI.' },
    ],
    "Conventional Deadlift (CAT)": [
        { en: 'CAT – explode as fast as possible every rep. General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3. Speed/form focus.', pl: 'CAT – eksploduj maksymalnie szybko każde powt. Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3. Prędkość/forma.' },
    ],
    "Conventional Deadlift (Heavy Double)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. Heavy double @ RPE 9.5. Very close to max.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. Ciężki dubel @ RPE 9.5. Bardzo blisko max.' },
    ],
    "Conventional Deadlift (Heavy Triple)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. Heavy triple @ RPE 9.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. Ciężki tripel @ RPE 9.' },
    ],
    "Conventional Deadlift (Light)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3 (skip 85%, 95%).  Light work @ 70% for speed.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3 (pomiń 85%, 95%).  Lekka praca @ 70% na prędkość.' },
    ],
    "Conventional Deadlift (Max Single)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. JUDGMENT DAY. Your moment of glory.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. DZIEŃ SĄDU. Twój moment chwały.' },
    ],
    "Conventional Deadlift (ME)": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1.  Max Effort single.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1.  Max Effort singiel.' },
    ],
    "Conventional Deadlift E2MOM": [
        { en: 'E2MOM – every 2 min: 3-5 reps, rest remainder. Grip/form priority. Aim 3-5 reps all 6 sets. General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2.', pl: 'E2MOM – co 2 min: 3-5 powt., reszta odpoczynek. Chwyt/forma priorytet. Celuj 3-5 powt. wszystkie 6 serie. Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2.' },
    ],
    "Deficit Snatch Grip Deadlift": [
        { en: 'General warm-up (see Deadlift warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka martwego ciągu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3 (lżejsze %: deficyt + snatch grip).' },
    ],
    "Glute Ham Raise (eccentric only)": [
        { en: '3-5 sec lowering (eccentric only). Cheat up any way possible.', pl: '3-5 sek opuszczanie (tylko ekscentryk). Oszukiwane powtórzenia w górę (zegnij się w biodrach).' },
    ],
    "Heels-Off Narrow Leg Press": [
        { en: 'Knees out, deep stretch at the bottom. Last set: triple drop set.', pl: 'Kolana na zewnątrz, głębokie rozciągnięcie. Ostatnia seria: potrójny drop set.', weeks: [11, 12] },
    ],
    "Low Bar Squat": [
        { en: 'General warm-up (see Squat warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1 (heavy days).', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka przysiadu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1 (ciężkie dni).' },
    ],
    "Low Bar Squat (Ascension Test)": [
        { en: 'General warm-up (see Squat warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2.  ASCENSION TEST.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka przysiadu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2.  TEST ASCENSJI.' },
    ],
    "Low Bar Squat (Light)": [
        { en: 'General warm-up (see Squat warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3 (skip 85%, 95%).  Light work @ 70% for speed.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka przysiadu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3 (pomiń 85%, 95%).  Lekka praca @ 70% na prędkość.' },
    ],
    "Low Bar Squat (ME)": [
        { en: 'General warm-up (see Squat warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1.  Max Effort single.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka przysiadu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1.  Max Effort singiel.' },
    ],
    "Low Pin Press": [
        { en: 'Set pins at your sticking point. Explosive press from dead stop. 📈 Target reps hit on ALL sets = +2.5 kg next session', pl: 'Ustaw piny na swoim martwym punkcie. Eksplozywne wyciskanie z martwego startu. 📈 Docelowe powt. na WSZYSTKICH seriach = +2.5 kg następna sesja' },
    ],
    "Paused Bench Press (AMRAP)": [
        { en: 'AMRAP drives progression! Weeks 1-6: ≥12 reps, Weeks 7-9: ≥10 reps, Weeks 10-12: ≥8 reps.', pl: 'AMRAP napędza progresję! Tyg. 1-6: ≥12 powt., Tyg. 7-9: ≥10 powt., Tyg. 10-12: ≥8 powt.' },
    ],
    "Paused Bench Press (Ascension Test)": [
        { en: 'General warm-up (see Bench warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2. All paused. ASCENSION TEST – AMRAP @ 85%.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka wyciskania) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2. Wszystkie z pauzą. TEST ASCENSJI – AMRAP @ 85%.' },
    ],
    "Paused Bench Press (Back-off)": [
        { en: 'Technique work - focus on perfect form, controlled tempo.', pl: 'Praca nad techniką - skup się na idealnej formie, kontrolowane tempo.' },
    ],
    "Paused Bench Press (Light)": [
        { en: 'General warm-up (see Bench warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3 (skip 85%, 95%). All paused. Light work @ 70% for speed.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka wyciskania) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3 (pomiń 85%, 95%). Wszystkie z pauzą. Lekka praca @ 70% na prędkość.' },
    ],
    "Paused Bench Press (ME)": [
        { en: 'General warm-up (see Bench warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. All paused. Max Effort – work up to 90-95% 1RM.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka wyciskania) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2, 95% × 1. Wszystkie z pauzą. Max Effort – dojdź do 90-95% 1RM.' },
    ],
    "Paused Low Bar Squat": [
        { en: 'General warm-up (see Squat warm-up tip above) → Barbell warm-up: Empty bar × 8-10, 50% × 5, 70% × 3, 85% × 2. All paused. 2-sec pause in hole. Progression weeks 1-8: +2.5kg weekly. Weeks 9-16: fixed weight to prioritize deadlift peaking.', pl: 'Rozgrzewka ogólna (patrz powyżej – rozgrzewka przysiadu) → Rozgrzewka sztangą: Pusty gryf × 8-10, 50% × 5, 70% × 3, 85% × 2. Wszystkie z pauzą. 2-sek pauza w dole. Progresja tyg. 1-8: +2.5kg co tydzień. Tyg. 9-16: stały ciężar (priorytet peaking).' },
    ],
    "Paused Squat": [
        { en: '80% of Monday squat weight. 2 full seconds in the hole - no bounce.', pl: '80% ciężaru z poniedziałkowego przysiadu. 2 pełne sekundy w dołku – bez odbijania.' },
    ],
    "Power Hanging Leg Raises": [
        { en: 'Explosive - knees to chest fast, slow eccentric (3-5 sec), full stretch at bottom.', pl: 'Wybuchowo – kolana do klatki szybko, wolny ekscentryk (3-5 sek), pełne rozciągnięcie na dole.' },
    ],
    "Single-Leg Machine Hip Thrust": [
        { en: 'Explosive reps. Last set: 20 sec isometric hold + partials.', pl: 'Eksplozywne powtórzenia. Ostatnia seria: 20 sek izometryczny hold + częściówki.', weeks: [11, 12] },
    ],
    "Spoto Press": [
        { en: 'Stop bar 4-8 cm above chest, hold 1 second, then press explosively. 📈 Target reps hit on ALL sets = +2.5 kg next session', pl: 'Zatrzymaj sztangę 4-8 cm nad klatką, trzymaj 1 sek, potem wyciśnij eksplozywnie. 📈 Docelowe powt. na WSZYSTKICH seriach = +2.5 kg następna sesja' },
    ],
    "Standing Barbell Military Press": [
        { en: 'Strict, no leg drive. Proud chest, squeeze delts.', pl: 'Ścisłe, bez odbicia nóg. Dumna klatka, ścisk deltków.' },
    ],
    "Tricep Giant Set": [
        { en: '~10 second rest between exercises. 2 minute rest between sets. Hit 25 reps on Banded Skullcrushers to progress weight.', pl: '~10 sek przerwy między ćwiczeniami. 2 min przerwy między seriami. Zrób 25 powt. Skullcrusherów z gumą, by progresnąć ciężar.' },
    ],
    "Walking Lunges": [
        { en: 'Long strides, do not push off back leg. Last set: rest-pause to failure.', pl: 'Długie kroki, nie odpychaj się tylną nogą. Ostatnia seria: rest-pause do upadku.', weeks: [11, 12] },
    ],
    "Walking Lunges (DB)": [
        { en: 'Long strides, do not push off back leg.', pl: 'Długie kroki, nie odpychaj się tylną nogą.' },
    ],
};

/**
 * Most specific match wins: a week-scoped tip applies only inside its weeks,
 * and an unscoped one is the fallback for every other week.
 */
export const getVariantTip = (name: string, week: number): VariantTip | undefined => {
    const list = EXERCISE_VARIANT_TIPS[name];
    if (!list?.length) return undefined;
    return list.find(v => v.weeks?.includes(week)) ?? list.find(v => !v.weeks);
};
